* Name and address
#+begin_src elisp
(setq user-full-name "Eddie Groves"
      user-mail-address "eddiegroves@gmail.com")
#+end_src

* Font

Current font is [[https://github.com/source-foundry/Hack][Hack font]] with a bunch of glyphs (icons) added to it. The font
must be installed already, see [[https://github.com/ryanoasis/nerd-fonts][Nerd Fonts]].

#+begin_src elisp
(setq doom-font (font-spec :family "Hack Nerd Font" :size 18 :weight 'semi-light))
#+end_src

* Theme

https://github.com/hlissner/emacs-doom-themes
https://draculatheme.com/

#+begin_src elisp
(setq doom-theme 'doom-dracula)
#+end_src

* Line numbers

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src elisp
(setq display-line-numbers-type nil)
#+end_src

* Backup settings

Reasonable looking backup settings from a [[https://stackoverflow.com/a/18330742/5769][Stack Overflow answer]].

#+begin_src elisp
(defvar --backup-directory (concat user-emacs-directory "backups"))
(if (not (file-exists-p --backup-directory))
    (make-directory --backup-directory t))
(setq backup-directory-alist `(("." . ,--backup-directory)))
(setq make-backup-files t       ; backup of a file the first time it is saved.
      backup-by-copying t       ; don't clobber symlinks
      version-control t         ; version numbers for backup files
      delete-old-versions t     ; delete excess backup files silently
      delete-by-moving-to-trash t
      kept-old-versions 6       ; oldest versions to keep when a new numbered backup is made (default: 2)
      kept-new-versions 9       ; newest versions to keep when a new numbered backup is made (default: 2)
      auto-save-default t       ; auto-save every buffer that visits a file
      auto-save-timeout 20      ; number of seconds idle time before auto-save (default: 30)
      auto-save-interval 200    ; number of keystrokes between auto-saves (default: 300)
      )
#+end_src

* Start-up

Start maximized

#+begin_src elisp
(add-hook 'window-setup-hook #'toggle-frame-maximized)
#+end_src

* TODO White space :disabled:

Add this back when I see the need, and document it better.

#+begin_src elisp :tangle no
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+end_src

* Org mode

Always enable spelling

#+begin_src elisp
(add-hook 'org-mode-hook 'turn-on-flyspell)
#+end_src

Disable visual line mode

#+begin_src elisp
(add-hook 'org-mode-hook (lambda ()
                              (visual-line-mode -1)))
#+end_src

Match the Doom screenshot

#+begin_src elisp
(setq org-ellipsis " ▼ ")
#+end_src

Always auto fill paragraphs

#+begin_src elisp
(add-hook 'org-mode-hook 'turn-on-auto-fill)
#+end_src

Always start with things hidden

#+begin_src elisp
(setq org-hide-block-startup t)
(setq org-startup-folded t)
#+end_src

Disable :ATTACH: tag when attaching documents

#+begin_src elisp
(setq org-attach-auto-tag nil)
#+end_src

Try to fix indention of source blocks?
https://emacs.stackexchange.com/questions/9472/org-mode-source-block-doesnt-respect-parent-buffer-indentation

#+begin_src elisp
(setq org-src-preserve-indentation nil
      org-edit-src-content-indentation 0)
#+end_src
